services:

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"   
      - "443:443"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - certbot_webroot:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - website    
      - grafana    
      - prometheus 
    networks:
      - monitoring
    restart: unless-stopped
  website: 
    image: zhenyapetko/portfolio-site:latest
    build: .  
    depends_on:  # Ждёт Prometheus
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_webroot:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    command: [
      "sh", "-c",
      "sleep 30 && certbot certonly --webroot -w /var/www/certbot -d e-petko.dev -d www.e-petko.dev -d grafana.e-petko.dev -d prometheus.e-petko.dev --email zhen.petko@gmail.com --agree-tos --non-interactive --keep-until-expiring --expand"
    ]
    networks:
      - monitoring  
    restart: on-failure

  prometheus:  
    image: prom/prometheus:latest 
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml  # Конфиг (создай файлы)
      - prometheus_data:/prometheus  # Persist data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=grafana.e-petko.dev
      - GF_SERVER_ROOT_URL=https://grafana.e-petko.dev/
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped

  node-exporter:  # Exporter для системных metrics (подключает к Prometheus)
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  certbot_webroot:
  certbot_certs:


networks:
  monitoring:
    driver: bridge