services:

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"   
      - "443:443"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # ✅ БУДЕМ СОЗДАВАТЬ ЭТОТ ФАЙЛ
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/00-site.conf:ro
      - certbot_webroot:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - website    
      - grafana    
      - prometheus 
    networks:
      - monitoring
    restart: unless-stopped
  website: 
    image: zhenyapetko/portfolio-site:latest
    build: .  
    depends_on:  # Ждёт Prometheus
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

  certbot: # НОВЫЙ СЕРВИС: Certbot
    image: certbot/certbot
    volumes:
      - certbot_webroot:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    networks:
      - monitoring  
    restart: unless-stopped

  prometheus:  
    image: prom/prometheus:latest  
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml  # Конфиг (создай файлы)
      - prometheus_data:/prometheus  # Persist data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    restart: unless-stopped

  grafana:  # Dashboard на базу Prometheus
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana  # Persist dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Измени password!
    depends_on:
      - prometheus
    networks:
      - monitoring
    restart: unless-stopped

  node-exporter:  # Exporter для системных metrics (подключает к Prometheus)
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  certbot_webroot:
  certbot_certs:


networks:
  monitoring:
    driver: bridge