baseURL = "https://e-petko.dev/"
languageCode = "ru-ru"
title = "Zhenya Petko Portfolio"
theme = "beautifulhugo"
favicon = "favicon.ico"

[params]
  Name = "Петько Евгений"  # Замени на своё имя
  Description = "Студент DevOps, люблю контейнеры, инфраструктуру и код. Здесь моё портфолио."
  Email = "zheny.petko@gmail.com"  # Замени на свой email
  GitHub = "https://github.com/zhenyapetko"  # Замени на свой профиль


