global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'website'
    static_configs:
      - targets: ['website:80']  # Metrics с сайта
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']  # Системные metrics